In [1]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.


In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec,KeyedVectors

In [4]:
import gensim.downloader as api
wv=api.load("word2vec-google-news-300")
vec_king=wv['king']

In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [6]:
vec_king.shape

(300,)

In [7]:
wv['soccer']

array([-0.07666016,  0.11035156,  0.35351562, -0.07910156, -0.05004883,
       -0.296875  ,  0.109375  , -0.359375  , -0.08740234, -0.0703125 ,
        0.20800781, -0.24511719, -0.05566406,  0.2421875 ,  0.02355957,
       -0.00866699,  0.02685547,  0.40234375,  0.17480469, -0.01660156,
       -0.20410156,  0.5       , -0.08984375, -0.14355469,  0.05541992,
        0.09082031,  0.11425781,  0.15429688,  0.13476562,  0.2265625 ,
        0.04418945,  0.03710938, -0.11621094, -0.11328125, -0.01647949,
       -0.12695312,  0.29882812, -0.12597656,  0.10302734,  0.31640625,
        0.00126648, -0.08837891,  0.12695312,  0.15820312, -0.07177734,
       -0.2109375 ,  0.31640625, -0.20800781,  0.00096893,  0.32421875,
        0.07128906,  0.07128906, -0.09228516, -0.02270508,  0.09570312,
       -0.29882812, -0.06591797, -0.07080078, -0.07421875, -0.23535156,
       -0.28320312, -0.20214844, -0.16210938,  0.22070312, -0.02368164,
       -0.10644531,  0.01965332, -0.05908203,  0.23730469,  0.02

In [8]:
wv.most_similar('soccer')

[('Soccer', 0.7622618675231934),
 ('football', 0.7313547730445862),
 ('basketball', 0.6810985207557678),
 ('volleyball', 0.6647275686264038),
 ('softball', 0.6443415284156799),
 ('lacrosse', 0.6438060402870178),
 ('water_polo', 0.6297686100006104),
 ('hockey', 0.6270937323570251),
 ('tennis', 0.6163383722305298),
 ('futbol', 0.6026160717010498)]

In [9]:
wv.most_similar('sad')

[('saddening', 0.7273085713386536),
 ('Sad', 0.6610826849937439),
 ('saddened', 0.6604382395744324),
 ('heartbreaking', 0.6573508381843567),
 ('disheartening', 0.6507317423820496),
 ('Meny_Friedman', 0.6487058401107788),
 ('parishioner_Pat_Patello', 0.6475860476493835),
 ('saddens_me', 0.6407119035720825),
 ('distressing', 0.6399092674255371),
 ('reminders_bobbing', 0.6357713341712952)]

In [10]:
wv.similarity("hockey","movie")

0.19126397

In [11]:
vec=wv['king']-wv['man']+wv['woman']

In [12]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [13]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [15]:
import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

# Example data
sentences = [
    "The quick brown fox jumps over the lazy dog",
    "I love machine learning and natural language processing"
]


In [16]:
# Tokenizing sentences
tokenized_sentences = [word_tokenize(sentence.lower()) for sentence in sentences]


In [17]:
# Training Word2Vec model
model = Word2Vec(tokenized_sentences, vector_size=100, window=5, min_count=1, workers=4)


In [18]:

import numpy as np

def average_word_vectors(words, model, num_features):
    # Initialize an empty array for storing the sum of word vectors
    feature_vector = np.zeros((num_features,), dtype="float32")
    num_words = 0
    
    for word in words:
        if word in model.wv:
            num_words += 1
            feature_vector = np.add(feature_vector, model.wv[word])
    
    # Divide the result by the number of words to get the average
    feature_vector = np.divide(feature_vector, num_words)
    return feature_vector

# Compute average word vectors for each sentence
avg_word_vectors = [average_word_vectors(sentence, model, 100) for sentence in tokenized_sentences]
print(avg_word_vectors)


[array([-3.2642340e-05,  2.0062900e-03,  1.8489787e-03,  1.0103183e-03,
       -2.6750830e-03, -4.6689129e-03, -7.1732327e-04,  4.8282803e-03,
       -1.2002370e-03, -3.4589458e-03,  2.6148560e-03, -2.8761795e-03,
       -3.6701942e-03, -5.1619828e-04, -1.2052547e-03,  5.4026372e-04,
        2.1280758e-03, -8.1833190e-04,  2.5723223e-04, -5.7656220e-03,
        1.6080072e-03,  2.1366586e-03,  2.1121288e-03, -4.1919309e-04,
       -9.0409070e-05,  5.2831159e-04, -3.9450643e-03,  3.4916368e-03,
        9.4223018e-05, -6.4984034e-04, -3.1270501e-03, -6.7241670e-04,
        4.9582762e-03,  7.1314367e-05, -1.8207367e-03, -7.4380753e-04,
        2.5356472e-03, -8.9152833e-04, -2.0588741e-03,  3.7216383e-04,
       -1.4029252e-03,  1.2955902e-03, -2.5489770e-03,  1.7961053e-03,
       -1.3074016e-03, -1.0600669e-03, -2.0880164e-03,  6.7200954e-04,
        6.9397019e-04,  3.5926902e-03, -1.2687969e-03,  6.8659318e-04,
       -2.6330200e-04,  1.3815806e-03,  1.2365949e-03, -2.2472774e-03,
     

In [19]:
long_sentence = "Natural language processing enables computers to understand and process human language, opening up a wide range of applications and opportunities."


In [20]:
import numpy as np

def average_word_vectors(words, model, num_features):
    feature_vector = np.zeros((num_features,), dtype="float32")
    num_words = 0
    
    for word in words:
        if word in model.wv:
            num_words += 1
            feature_vector = np.add(feature_vector, model.wv[word])
    
    if num_words > 0:
        feature_vector = np.divide(feature_vector, num_words)
    return feature_vector

# Tokenize the sentence
tokenized_sentence = word_tokenize(long_sentence.lower())

# Compute the average word vector
avg_vector = average_word_vectors(tokenized_sentence, model, 100)
print(avg_vector)


[-5.15828980e-03  3.60014127e-03 -3.83104943e-03 -5.77313185e-04
  5.80753153e-03  2.68221088e-03 -1.83408687e-04  3.74676008e-03
 -3.60507402e-03  2.19565909e-03 -2.15225364e-03 -1.22149475e-04
  9.13486219e-05  1.11344794e-03  2.80632381e-03 -2.59419437e-03
  3.28864227e-03  5.55380946e-03 -2.87264585e-03 -2.32708454e-03
 -1.42694870e-03 -5.57202334e-03  4.32762178e-03  1.79380804e-04
  1.23626541e-03 -4.44571866e-04  3.26041947e-03  4.95891878e-03
 -5.00487862e-03  2.70424341e-03  5.88620221e-03 -3.09525430e-03
 -3.38323787e-03 -5.22979954e-03  1.24752114e-03 -6.80992380e-04
  1.56002631e-03  2.28539994e-03  2.45538104e-04  3.34972702e-03
  6.17626531e-04 -2.00324901e-03 -4.01973771e-03  4.75130836e-03
  4.09453129e-03  9.93141672e-04  3.08031775e-03 -1.48546521e-03
 -1.40350312e-04 -2.81354412e-03  3.83684481e-03 -1.00490882e-03
 -6.70522451e-04 -5.12567302e-03 -4.68481565e-03 -3.04244272e-03
 -2.01377482e-03 -1.80679746e-03 -1.68225297e-03 -2.83669098e-03
  1.67002750e-03 -1.93910