In [3]:
pip install pandas


   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.5 MB 7.1 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.5 MB 6.1 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.5 MB 4.3 MB/s eta 0:00:03
   ----------- ---------------------------- 3.4/11.5 MB 4.3 MB/s eta 0:00:02
   ------------ --------------------------- 3.7/11.5 MB 4.3 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.5 MB 4.1 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.5 MB 4.1 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.5 MB 4.1 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.5 MB 4.0 MB/s eta 0:00:02
   ----------------------------- ---------- 8.4/11.5 MB 4.0 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 4.0 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.5 MB 4.0 MB/s eta 0:00:01
   --

In [6]:
pip install chardet


Note: you may need to restart the kernel to use updated packages.


In [20]:
import chardet
import pandas as pd



In [21]:

messages=pd.read_csv('spam.csv',sep=',',encoding='latin1')

In [22]:
messages.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [23]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [25]:
#Drop the Columns
messages.drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace = True)

In [26]:
 # Rename the columns name
messages.rename(columns = {'v1': 'target', 'v2': 'text'}, inplace = True)

In [27]:
messages

target                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham            Will �_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [28]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\priya/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [32]:
from nltk.stem import WordNetLemmatizer
le=WordNetLemmatizer()
from nltk.corpus import stopwords

In [37]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['text'][i])
    review=review.lower()
    review=review.split()
    review=[le.lemmatize(word,pos='v') for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [38]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joke wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'mobile months u r entitle update latest colour mobiles camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day days tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',


### Creation of BagOfWord

In [48]:
pip install scikit-learn


   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.0 MB 6.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.0 MB 3.4 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.0 MB 3.6 MB/s eta 0:00:03
   ----------- ---------------------------- 3.1/11.0 MB 4.4 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/11.0 MB 4.1 MB/s eta 0:00:02
   ------------------- -------------------- 5.2/11.0 MB 4.1 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.0 MB 4.1 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.0 MB 4.0 MB/s eta 0:00:02
   --------------------------- ------------ 7.6/11.0 MB 4.0 MB/s eta 0:00:01
   ------------------------------ --------- 8.4/11.0 MB 4.0 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 4.0 MB/s eta 0:00:01
   --

In [67]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=1000,binary=True)

In [68]:
X=cv.fit_transform(corpus).toarray()

In [69]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [70]:
X.shape

(5572, 1000)

In [71]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

### N-Grams

In [72]:
cv.vocabulary_

{'go': np.int64(331),
 'point': np.int64(648),
 'crazy': np.int64(168),
 'available': np.int64(49),
 'great': np.int64(341),
 'world': np.int64(971),
 'la': np.int64(435),
 'get': np.int64(322),
 'wat': np.int64(932),
 'ok': np.int64(594),
 'lar': np.int64(439),
 'joke': np.int64(422),
 'wif': np.int64(954),
 'free': np.int64(300),
 'entry': np.int64(248),
 'wkly': np.int64(965),
 'comp': np.int64(144),
 'win': np.int64(957),
 'cup': np.int64(172),
 'final': np.int64(284),
 'st': np.int64(804),
 'may': np.int64(505),
 'text': np.int64(844),
 'receive': np.int64(690),
 'question': np.int64(673),
 'std': np.int64(810),
 'txt': np.int64(891),
 'rate': np.int64(681),
 'apply': np.int64(36),
 'dun': np.int64(227),
 'say': np.int64(732),
 'early': np.int64(231),
 'already': np.int64(21),
 'nah': np.int64(561),
 'think': np.int64(852),
 'usf': np.int64(910),
 'live': np.int64(471),
 'around': np.int64(41),
 'though': np.int64(856),
 'freemsg': np.int64(301),
 'hey': np.int64(367),
 'week': np

In [85]:
## Create the Bag OF Words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=1000,binary=True,ngram_range=(1,3))
X=cv.fit_transform(corpus).toarray()

In [86]:
cv.vocabulary_

{'go': np.int64(330),
 'point': np.int64(655),
 'crazy': np.int64(184),
 'available': np.int64(44),
 'great': np.int64(347),
 'world': np.int64(973),
 'get': np.int64(321),
 'wat': np.int64(937),
 'ok': np.int64(596),
 'lar': np.int64(451),
 'joke': np.int64(434),
 'wif': np.int64(956),
 'free': np.int64(301),
 'entry': np.int64(255),
 'wkly': np.int64(967),
 'comp': np.int64(161),
 'win': np.int64(959),
 'final': np.int64(287),
 'st': np.int64(797),
 'may': np.int64(516),
 'text': np.int64(838),
 'receive': np.int64(696),
 'question': np.int64(681),
 'std': np.int64(805),
 'txt': np.int64(884),
 'rate': np.int64(688),
 'apply': np.int64(33),
 'free entry': np.int64(303),
 'dun': np.int64(238),
 'say': np.int64(734),
 'early': np.int64(242),
 'already': np.int64(18),
 'think': np.int64(847),
 'usf': np.int64(913),
 'live': np.int64(480),
 'around': np.int64(36),
 'though': np.int64(851),
 'freemsg': np.int64(305),
 'hey': np.int64(386),
 'week': np.int64(944),
 'word': np.int64(971),
 

In [87]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [88]:
X.shape

(5572, 1000)